version: '3.7'
services:
  vite-app:
    container_name: vite-app
    build:
      context: .
      dockerfile: Dockerfile
    image: s1xz/bookbix-frontend
    restart: unless-stopped
    ports:
      - '${CLIENT_PORT}:${SERVER_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      PORT: ${SERVER_PORT}
      NODE_ENV: ${NODE_ENV}
    working_dir: /app
