version: '3.7'
services:
  vite-app:
    container_name: vite-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT}:${SERVER_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      PORT: ${SERVER_PORT}
      NODE_ENV: ${NODE_ENV}
    working_dir: /app
    networks:
      - backbone
  backend-app:
    image: s1xz/bookbix-backend:latest
    depends_on:
      - db
    ports:
      - "${BACKEND_SERVER_PORT}:3000"
    restart: unless-stopped
    environment:
      MONGODB_DBURL: mongodb://${MONGO_INITDB_USER}:${MONGO_INITDB_PWD}@db:27017/${MONGO_INITDB_DATABASE}?authSource=${MONGO_INITDB_DATABASE}
      MONGODB_DBNAME: ${MONGO_INITDB_DATABASE}
      PORT: 3000
    networks:
      - backbone
  db:
    image: mongo:4.0.2
    restart: unless-stopped
    ports:
      - "${DB_CLIENT_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USER}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PWD}
    volumes:
      - ./mongoscripts:/docker-entrypoint-initdb.d:ro
      - ./data/db:/data/db
    networks:
      - backbone
networks:
  backbone:
    driver: bridge